version: '3.4'

services:
  eshop.web.mvc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - CatalogAPIDocker=http://eshop.catalog.api/api/v1.0/
      - BasketAPIDocker=http://eshop.basket.api/api/basket/
    ports:
      - "2020:80"

  eshop.catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - DockerConnectionString=${ESHOP_CATALOG_MSQL_CONNECTION_STRING}
      - RabbitMQConnection = rabbitmq
      - EventBusRabbitMQUsername = ${ESHOP_RABBITMQ_DEFAULT_USERNAME}
      - EventBusRabbitMQPassword = ${ESHOP_RABBITMQ_DEFAULT_PASSWORD}
    ports:
      - "4040:80"

  eshop.basket.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RedisConnectionString=basketdata 
      - RabbitMQConnection = rabbitmq
      - EventBusRabbitMQUsername = ${ESHOP_RABBITMQ_DEFAULT_USERNAME}
      - EventBusRabbitMQPassword = ${ESHOP_RABBITMQ_DEFAULT_PASSWORD}
    ports:
      - "3001:80"

  rabbitmq:
    ports:
        - "15672:15672"
        - "5672:5672"
  sqldata:
    environment:
      - MSSQL_SA_PASSWORD=${ESHOP_MSQL_PASS}
      - ACCEPT_EULA=Y
    ports:
      - 2001:1433
    volumes:
      - eshop-data:/var/opt/mssql

  basketdata:
    expose:
      - "6379"

  

volumes:
  eshop-data:
     external: false
