version: '3.4'

services:
  eshop.web.mvc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - CatalogAPIDocker=http://eshop.catalog.api/api/v1.0/catalog/
    ports:
      - "2020:80"

  eshop.catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - DockerConnectionString=Server=sqldata;Database=EShop_CatalogDb;User Id=sa;Password=Mravki123#
    ports:
      - "4040:80"

  sqldata:
    environment:
      - MSSQL_SA_PASSWORD=Mravki123#
      - ACCEPT_EULA=Y
    ports:
      - 2001:1433
    volumes:
      - eshop-data:/var/opt/mssql

volumes:
  eshop-data:
     external: false