version: '3.4'

services:
      
  eshop.web.mvc:
    image: ${DOCKER_REGISTRY-}eshopwebmvc:${TAG:-latest}
    build:
      context: .
      dockerfile: WebApp/EShop.Web.MVC/Dockerfile
    depends_on:
        - ocelotapigw

  ocelotapigw:
    image: ${DOCKER_REGISTRY-}ocelotapigw
    build:
      context: .
      dockerfile: Gateway/WebGateway/Ocelot/OcelotAPIGw/Dockerfile
    depends_on:
      - eshop.catalog.api
      - eshop.basket.api
      - eshop.orders.api
      - web.bff.shoppingaggregator

  web.bff.shoppingaggregator:
    image: ${DOCKER_REGISTRY-}webbffshoppingaggregator
    build:
      context: .
      dockerfile: Gateway/WebAggregator/Web.BFF.ShoppingAggregator/Dockerfile

  eshop.catalog.api:
    image: ${DOCKER_REGISTRY-}eshopcatalogapi:${TAG:-latest}
    build:
      context: .
      dockerfile: Services/Catalog/EShop.Catalog.API/Dockerfile
    depends_on:
        - sqldata
        - rabbitmq
  
  eshop.basket.api:
    image: ${DOCKER_REGISTRY-}eshopbasketapi
    build:
      context: .
      dockerfile: Services/Basket/EShop.Basket.API/Dockerfile
    depends_on:
      - basketdata
      - rabbitmq
  
  eshop.orders.api:
    image: ${DOCKER_REGISTRY-}eshopordersapi
    build:
      context: .
      dockerfile: Services/Orders/EShop.Orders.API/Dockerfile
    depends_on:
      - sqldata
      - rabbitmq

  sqldata:
    image: mcr.microsoft.com/mssql/server:2022-latest

  basketdata:
     image: redis

  rabbitmq:
    image: rabbitmq:3-management-alpine