version: '3.4'

services:
 
  eshop.web.mvc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - GatewayAPI=http://ocelotapigw/gw/v1/       
    ports:
      - "2020:80"

  eshop.web.spa.admin:
    ports:
       - 7077:80
    volumes:
       - '.:/app'
       - '/app/node_modules'

  ocelotapigw:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "9010:80"

  web.bff.shoppingaggregator:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80 
      - BasketAPIDocker=http://eshop.basket.api/api/v1/
      - OrderAPIDocker=http://eshop.orders.api/api/v1/
    ports:
      - "6060:80"

  eshop.catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - CatalogDockerDbConnectionString=${ESHOP_CATALOG_MSQL_CONNECTION_STRING}
      - RabbitMQConnection=rabbitmq
      - EventBusRabbitMQUsername=${ESHOP_RABBITMQ_DEFAULT_USERNAME}
      - EventBusRabbitMQPassword=${ESHOP_RABBITMQ_DEFAULT_PASSWORD}
    ports:
      - "4040:80"

  eshop.basket.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RedisConnectionString=basketdata 
      - RabbitMQConnection=rabbitmq
      - EventBusRabbitMQUsername=${ESHOP_RABBITMQ_DEFAULT_USERNAME}
      - EventBusRabbitMQPassword=${ESHOP_RABBITMQ_DEFAULT_PASSWORD}
    ports:
      - "3001:80"

  eshop.orders.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - OrderingDb=${ESHOP_ORDER_MSQL_CONNECTION_STRING}
      - RabbitMQConnection=rabbitmq
      - EventBusRabbitMQUsername=${ESHOP_RABBITMQ_DEFAULT_USERNAME}
      - EventBusRabbitMQPassword=${ESHOP_RABBITMQ_DEFAULT_PASSWORD}
    ports:
      - "5015:80"

  rabbitmq:
    ports:
      - "15672:15672"
      - "5672:5672"
  sqldata:
    environment:
      - MSSQL_SA_PASSWORD=${ESHOP_MSQL_PASS}
      - ACCEPT_EULA=Y
    ports:
      - 2001:1433
    volumes:
      - eshop-data:/var/opt/mssql

  basketdata:
    expose:
      - "6379"

volumes:
  eshop-data:
     external: false