version: '3.4'

services:
  eshop.web.mvc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - CatalogAPIDocker=http://eshop.catalog.api/api/v1.0/catalog/
      - BasketAPIDocker=http://eshop.basket.api/api/basket/
    ports:
      - "2020:80"

  eshop.catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - DockerConnectionString=${ESHOP_CATALOG_MSQL_CONNECTION_STRING}
    ports:
      - "4040:80"

  eshop.basket.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RedisConnectionString=basketdata 
    ports:
      - "3001:80"

  sqldata:
    environment:
      - MSSQL_SA_PASSWORD=${ESHOP_MSQL_PASS}
      - ACCEPT_EULA=Y
    ports:
      - 2001:1433
    volumes:
      - eshop-data:/var/opt/mssql

  basketdata:
    expose:
      - "6379"

  

volumes:
  eshop-data:
     external: false
