version: '3.4'

services:
 
  eshop.web.mvc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - GatewayAPI=http://ocelotapigw/gw/
    ports:
      - "2020:80"

  eshop.catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - DockerDbConnectionString=${ESHOP_CATALOG_MSQL_CONNECTION_STRING}
      - RabbitMQConnection=rabbitmq
      - EventBusRabbitMQUsername=guest
      - EventBusRabbitMQPassword=guest
    ports:
      - "4040:80"

  eshop.basket.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RedisConnectionString=basketdata 
      - RabbitMQConnection=rabbitmq
      - EventBusRabbitMQUsername=${ESHOP_RABBITMQ_DEFAULT_USERNAME}
      - EventBusRabbitMQPassword=${ESHOP_RABBITMQ_DEFAULT_PASSWORD}
    ports:
      - "3001:80"

  rabbitmq:
    ports:
      - "15672:15672"
      - "5672:5672"
  sqldata:
    environment:
      - MSSQL_SA_PASSWORD=${ESHOP_MSQL_PASS}
      - ACCEPT_EULA=Y
    ports:
      - 2001:1433
    volumes:
      - eshop-data:/var/opt/mssql

  basketdata:
    expose:
      - "6379"

  ocelotapigw:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "9010:80"

volumes:
  eshop-data:
     external: false