global using Microsoft.Extensions.Logging;
global using Microsoft.AspNetCore.Mvc;
global using Xunit;
global using Moq;
global using FluentAssertions;
global using EShop.Basket.API.Repository;
global using EShop.Basket.API.Controllers;
global using EShop.Basket.API.Model;
global using EventBus.Abstractions;