global using Xunit;
global using FluentAssertions;
global using Moq;
global using MediatR;
global using EShop.Orders.Domain.AggregatesModel.OrderAggregate;
global using EShop.Orders.Domain.AggregatesModel.BuyerAggregate;
global using EShop.Orders.Domain.Events;
global using EShop.Orders.Domain.Exceptions;
global using EShop.Orders.Domain.SeedWork;