global using System.Data;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using Microsoft.EntityFrameworkCore.Storage;
global using EShop.Orders.Domain.SeedWork;
global using EShop.Orders.Domain.AggregatesModel.OrderAggregate;
global using EShop.Orders.Domain.AggregatesModel.BuyerAggregate;
global using EShop.Orders.Infrastructure.EntityConfigurations;
global using MediatR;
