name: Docker Compose Workflow

on:
  push:
    branches: 
      - master
    
jobs:
  build:
    runs-on: ubuntu-latest
        
    steps:
       - name: Checkout
         uses: actions/checkout@v2
         
       - name: Set Up Docker Compose
         run: |
           sudo apt-get install docker-compose
           docker-compose version 
         
       - name: Build and Run App
         run: |
           docker-compose ./docker-compose.yml ./docker-compose.override.yml --env-file .env build
           docker-compose -d ./docker-compose.yml -d ./docker-compose.override.yml --env-file .env up
           
       - name: Shut Down App
         run: |
           docker-compose down
