name: Application Tests

on: 
  push:
    branches: 
      - master
  pull_request:
    branches:
      - master
      
jobs:
  unittests:    
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
        name: Setup .NET Core SDK
          
      - uses: actions/setup-dotnet@v3.2.0
        with:
          dotnet-versions: 6.0
      - name: Install dependencies
        run: dotnet restore ./Services/Catalog/Catalog.UnitTest/Catalog.UnitTest.csproj
      - name: Build
        run: dotnet build ./Services/Catalog/Catalog.UnitTest/Catalog.UnitTest.csproj
      - name: Test
        run: dotnet test ./Services/Catalog/Catalog.UnitTest/Catalog.UnitTest.csproj --no-restore --verbosity normal
             
      - uses: actions/setup-dotnet@v3.2.0
        name: Setup .NET Core SDK
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-versions: 6.0
      - name: Install dependencies
        run: dotnet restore ./Services/Basket/Basket.UnitTest/Basket.UnitTest.csproj
      - name: Build
        run: dotnet build ./Services/Basket/Basket.UnitTest/Basket.UnitTest.csproj
      - name: Test
        run: dotnet test ./Services/Basket/Basket.UnitTest/Basket.UnitTest.csproj --no-restore --verbosity normal

      - uses: actions/setup-dotnet@v3.2.0
        name: Setup .NET Core SDK
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-versions: 6.0
      - name: Install dependencies
        run: dotnet restore ./Services/Orders/Orders.UnitTest/Orders.UnitTest.csproj
      - name: Build
        run: dotnet build ./Services/Orders/Orders.UnitTest/Orders.UnitTest.csproj
      - name: Test
        run: dotnet test ./Services/Orders/Orders.UnitTest/Orders.UnitTest.csproj --no-restore --verbosity normal
        
      - uses: actions/setup-dotnet@v3.2.0
        name: Setup .NET Core SDK
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-versions: 6.0
      - name: Install dependencies
        run: dotnet restore ./BuildingBloks/Events/EventBus.UnitTest/EventBus.UnitTest.csproj
      - name: Build
        run: dotnet build ./BuildingBloks/Events/EventBus.UnitTest/EventBus.UnitTest.csproj
      - name: Test
        run: dotnet test ./BuildingBloks/Events/EventBus.UnitTest/EventBus.UnitTest.csproj --no-restore --verbosity normal
        
  integrationtests:    
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3.2.0
        name: Setup .NET Core SDK
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-versions: 6.0
      - name: Install dependencies
        run: dotnet restore ./Services/Catalog/Catalog.IntegrationTest/Catalog.IntegrationTest.csproj
      - name: Build
        run: dotnet build ./Services/Catalog/Catalog.IntegrationTest/Catalog.IntegrationTest.csproj
      - name: Test
        run: dotnet test ./Services/Catalog/Catalog.IntegrationTest/Catalog.IntegrationTest.csproj --no-restore --verbosity normal
                
      - uses: actions/checkout@v3.2.0
        name: Setup .NET Core SDK
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-versions: 6.0
      - name: Install dependencies
        run: dotnet restore ./Services/Basket/Basket.IntegrationTest/Basket.IntegrationTest.csproj
      - name: Build
        run: dotnet build ./Services/Basket/Basket.IntegrationTest/Basket.IntegrationTest.csproj
      - name: Test
        run: dotnet test ./Services/Basket/Basket.IntegrationTest/Basket.IntegrationTest.csproj --no-restore --verbosity normal

      - uses: actions/checkout@v3.2.0
        name: Setup .NET Core SDK
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-versions: 6.0
      - name: Install dependencies
        run: dotnet restore ./Services/Orders/EShop.Orders.IntegrationTest/EShop.Orders.IntegrationTest.csproj
      - name: Build
        run: dotnet build ./Services/Orders/EShop.Orders.IntegrationTest/EShop.Orders.IntegrationTest.csproj
      - name: Test
        run: dotnet test ./Services/Orders/EShop.Orders.IntegrationTest/EShop.Orders.IntegrationTest.csproj --no-restore --verbosity normal
        
