name: Application Tests

on: 
  push:
    branches: 
      - master
  pull_request:
    branches:
      - master
      
jobs:
  unittest:    
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
        name: Setup .NET Core SDK
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-versions: 6.0.x
      - name: Test
        run: dotnet test ./Services/Catalog/Catalog.UnitTest/Catalog.UnitTest.csproj --no-restore --verbosity normal
